### PR TITLE
Run Travis tests on Linux

### PR DESCRIPTION
**Pull request by rwhogg**
This sets up Travis CI to run tests on Linux.

The result of my build is [here](https://travis-ci.org/rwhogg/homebrew-bob/builds/96195526)

### CODE REVIEW

**Comment by dunn** [comment]
I think it's still building on OSX because we're setting `language: objective-c`.  Might have to do some fancy things like the Science tap does: https://github.com/Homebrew/homebrew-science/blob/master/.travis.yml

**Comment by rwhogg** [comment]
Wow - I can't believe I didn't see that. I guess I saw the penguin icon and assumed all was well.

This is, IMO, a bug in Travis - I'll poke around their issue tracker and see if there's anything related to this.

Failing that, I'll try out some of the tricks from the science tap. Thanks for pointing me to that!

**Comment by rwhogg** [comment]
I filed https://github.com/travis-ci/travis-ci/issues/5272 to address the misleading icon. In the meantime, I'll try out some workarounds.

**Comment by rwhogg** [comment]
Looks like it's more-or-less working now. Granted, the build is choking on cloc-emacs, but given that it does the same thing on my local, I think it's on the right track.

I have to squash my commits and might have to tweak a bit more, but I hope this will be ready for merge by Monday at the latest.

Thanks for pointing out the Travis bug - if you hadn't found that, we would have had the most superficial "Linux" build in history!

**Comment by dunn** [comment]
Thanks so much!

**Comment by rwhogg** [comment]
I apologize that I haven't gotten it to work yet (don't be fooled by the green - I made it pass by adding `--skip-homebrew`, without realizing at first that it makes the test-bot do pretty much nothing)

I'm not sure why this is timing out on `brew readall` so frequently - I'll look into this some more tomorrow, but I'm not optimistic.

**Comment by dunn** [comment]
No worries! Thanks again!

**Comment by rwhogg** [comment]
This still isn't working. I'll try my best to take another look at this this weekend.

Tomorrow, I'm going to see Star Wars - really, really hoping it's good!

**Comment by dunn** [comment]
:rocket: :100:

**Comment by rwhogg** [comment]
I think I've finally got this to work acceptably. Until the Linuxbrew merge happens, the test results are going to be kind of ugly, but I think now we can be ready for it.

**Comment by dunn** [comment]
Awesome!

**Pull request closed without merging**
