### PR TITLE
olivetti 1.5.4

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
Requeuing these bad boys.

**Comment by dunn** [comment]
This is new and exciting: https://travis-ci.org/Homebrew/homebrew-emacs/builds/157018403#L4791

**Comment by dunn** [comment]
Since that error's only on Linux, let's just ignore it

**Comment by dunn** [comment]
.

**Comment by ilovezfs** [comment]
:ship:'d

**Pull request closed without merging**
