### PR TITLE
Delete unused formulae

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Delete all homebrew/emacs formulae that show no installations since analytics records began.

### CODE REVIEW

**Comment by rwhogg** [comment]
I'm admittedly a little startled by this, so my apologies. I want to emphasize that I mean no offense in any of this.

1. I'm not sure that "0 installs since analytics began" means the same thing to Emacs as it does to Core. Emacs is a niche editor that has become even nicher since Mac users have so many options now. Furthermore, newer versions already have a package manager built in. I therefore suspect (although feel free to prove me wrong with analytics and/or other research) that zero installs says more about the popularity of the tap altogether than of the individual formulae. My suspected reasons for this are a) general ignorance of homebrew-emacs among Emacs users or b) too few formulae to make it a compelling alternative and/or addition to package.el.

I've said "I'm not sure" and "I suspect" a lot here - these are, I must emphasize, hunches.

2. I won't take any such action unilaterally, but I would personally rather see homebrew-emacs moved out of the Homebrew GitHub organization in its current state rather than see more than half its formulae deleted. I'm not worried about losing access to the formulae I use (textmate-emacs, flycheck, dockerfile-mode, editorconfig-emacs, etc.); I would simply copy those to rwhogg/homebrew-thirdparty. Rather, it is simply my opinion that it would be a more fitting fate. Linuxbrew has done just fine after moving.

3. I think some of the arguments made by @mistydemeo and @ilovezfs on https://github.com/Homebrew/homebrew-games/pull/769#issuecomment-269638874 apply here too.

**Comment by dunn** [comment]
Yeah, this seem far too aggressive.  I use many of these on a daily basis and the rest are not unmaintained; I have been removing formula that don't actually work on macOS and Homebrew's Emacs.

**Comment by MikeMcQuaid** [comment]
> I won't take any such action unilaterally, but I would personally rather see homebrew-emacs moved out of the Homebrew GitHub organization in its current state rather than see more than half its formulae deleted.

Yep, that's fine with me. I guess the question is what, if any, in this tap would be considered eligible for core if this tap didn't exist. If the answer is "nothing": let's move this tap to e.g. under @dunn's personal account.

**Comment by dunn** [comment]
> I guess the question is what, if any, in this tap would be considered eligible for core if this tap didn't exist.

To move anything we'd first have to move the `EmacsFormula` code into Homebrew/brew: https://github.com/Homebrew/homebrew-emacs/blob/master/Homebrew/emacs_formula.rb

The majority of the formulae would probably fail to meet the popularity criteria of Core as well.

This repo can revert back to a personal one if you really don't think it fits under the organization, but it was you and @xu-cheng who encouraged me to make it an official tap last year.  Could you elaborate on how your thoughts have evolved since then?

**Comment by MikeMcQuaid** [comment]
> To move anything we'd first have to move the EmacsFormula code into Homebrew/brew: https://github.com/Homebrew/homebrew-emacs/blob/master/Homebrew/emacs_formula.rb
> 
> The majority of the formulae would probably fail to meet the popularity criteria of Core as well.

Ok, thanks.

> This repo can revert back to a personal one if you really don't think it fits under the organization, but it was you and @xu-cheng who encouraged me to make it an official tap last year. Could you elaborate on how your thoughts have evolved since then?

It's mainly two things: consolidation and bus factor.

Consolidation: we do a pretty bad job of supporting non-homebrew-core taps to the same standard as homebrew-core. This is partly them getting less attention (particularly around new macOS releases) and partly them being much easier to ignore. This is something I'd like to change so to improve this all around.

Bus factor: I think having Homebrew/* repos maintained by a single Homebrew maintainer makes them fit better as a personal repo for that Homebrew maintainer so that person can do what they want and other maintainers don't feel the need to keep an eye on or maintain that repo. Homebrew/science is an example of a Homebrew organisation repo where there's multiple non-core maintainers and a few core maintainers who help maintain it.

I don't want this to be seen as an edict from on high, though: please feel free to disagree with this.

**Comment by MikeMcQuaid** [comment]
Passing on this until a later migration.

**Pull request closed without merging**
