### PR TITLE
olivetti 1.5.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
🙆 thanks!

**Comment by ilovezfs** [comment]
@dunn btw, shouldn't these all have bottle :unneeded?

**Comment by dunn** [comment]
@ilovezfs I guess, but really I should get around to hooking it up to Jenkins so there _are_ bottles.

**Comment by ilovezfs** [comment]
Ah, I didn't realize that was the reason. I only noticed this because I use an alias for pulling that always passes --bottle and only don't use that when I'm intentionally skipping a bottle update (e.g., devel spec is only spec affected). But without the bottle :unneeded in the formula, brew pull --bottle errors out instead of just issuing a warning.

**Pull request closed without merging**
