### PR TITLE
inf-ruby 2.5.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by rwhogg** [comment]
I've restarted the Travis Linux build. If it fails again, IMO we should ignore it - the last time it failed, it was just a umask audit failure.

Not sure why it did that, but I'll try to investigate if there's something wrong with Travis tonight if it fails again.

**Comment by rwhogg** [comment]
And it failed literally right after I commented ⌛️

I'll just merge it; it passed on Mac and the important (install/test) commands passed on Linux.

Thanks a bunch @ilovezfs 😸

**Comment by rwhogg** [comment]
Sorry, hold that thought. BrewTestBot never built a bottle for this PR.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
