### PR TITLE
emacs_formula.rb: don't require cmd/*

### PR DESCRIPTION
**Pull request by bfontaine**
cc @dunn; not sure if I broke something here or not.

### CODE REVIEW

**Comment by dunn** [comment]
I think I just copied that from `cmd/install.rb`, so if it changing it there worked this should be fine. Thanks!

**Comment by dunn** [comment]
(Feel free to pull; you know that code better than me.)

**Comment by bfontaine** [comment]
In fact I just tested and both `require` are unnecessary :+1:

**Comment by dunn** [comment]
:ok_woman:

**Pull request closed without merging**
