### PR TITLE
elfeed 2.1.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
This repo is going to leave the Homebrew org, so it's been disconnected from Jenkins and bottles aren't being created.  Could you remove the bottle block?

**Comment by ilovezfs** [comment]
shouldn't we replace them with `bottle :unneeded`?

**Comment by dunn** [comment]
Well it's not that they're unneeded, it's just we can't make them anymore.

**Comment by ilovezfs** [comment]
@dunn `bottle :disable` is also an option

**Comment by dunn** [comment]
Oh yeah.  I'd be OK with that.  That would suggest that all third-party taps should be using `bottle :disable` in all their formulae unless they have their own bottle service, though.

**Comment by ilovezfs** [comment]
The issue is that without one of those, `brew pull` will die if passed the `--bottle` option.

**Comment by dunn** [comment]
> The issue is that without one of those, brew pull will die if passed the --bottle option.

Oh, I didn't realize that.

**Pull request merged**
