### PR TITLE
company-mode 0.9.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
Test failing because `/lost+found` doesn't exist on the Jenkins machines.

**Comment by ilovezfs** [comment]
why would it exist anywhere?

**Comment by dunn** [comment]
http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/lostfound.html

**Comment by dunn** [comment]
https://github.com/company-mode/company-mode/pull/609

**Comment by ilovezfs** [comment]
Yup, thx.

**Comment by dunn** [comment]
PR merged upstream.

**Comment by ilovezfs** [comment]
Closed in favor of https://github.com/Homebrew/homebrew-emacs/pull/505.

**Pull request closed without merging**
