### PR TITLE
Add a Ruby 1.8.7 entry to Travis

### PR DESCRIPTION
**Pull request by rwhogg**
Basically copied straight from main Homebrew's Travis file.

~~For now, I've done it as a separate entry, since I didn't have an install script up until now. I'm going to experiment a bit to see what gives the best results.~~

### CODE REVIEW

**Comment by rwhogg** [comment]
This is ready for merge whenever you're happy with it.

**Comment by dunn** [comment]
Thanks!

Do we still need the Ruby 2 version of Mavericks?

**Comment by rwhogg** [comment]
(Rather embarrassed that I had to look up on what version number corresponded to 'Mavericks") 

I ended up taking it out. I'll put it back in if you want it - it's entirely up to you. That said, I'm not entirely sure how much value additional variants are, and I don't want to use up Travis' resources unnecessarily.

**Comment by dunn** [comment]
Fine with me!

**Pull request closed without merging**
