### PR TITLE
pandoc-mode 2.19

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
@rwhogg would these be fixed by adding a newer default compiler to Travis? https://travis-ci.org/Homebrew/homebrew-emacs/builds/157104548#L4527

**Comment by rwhogg** [comment]
@dunn I'm not sure. I've opened https://github.com/Linuxbrew/homebrew-core/pull/859 to see if we can get `icu4c` bottled.

**Comment by dunn** [comment]
Oh, thanks!

**Comment by dunn** [comment]
Bleh: https://travis-ci.org/Homebrew/homebrew-emacs/builds/157104548#L4878

I guess add
```elisp
      (add-to-list 'load-path "#{Formula["homebrew/emacs/cl-lib"].opt_elisp}") 
```
to the test file.

**Comment by dunn** [comment]
Ok, this is getting silly https://travis-ci.org/Homebrew/homebrew-emacs/builds/157428705#L4930

**Comment by dunn** [comment]
Oh, it's trying to build bottles.  Could you rebase?

**Comment by ilovezfs** [comment]
@dunn rebased!

**Comment by dunn** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
