### PR TITLE
csharp-mode 0.9.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
Ignore Travis as usual.

**Comment by ilovezfs** [comment]
@dunn so when do we pull the proverbial plug on Travis

**Comment by dunn** [comment]
Maybe we should turn it off until Linuxbrew is better sync-ed up with brew core?  Dunno if that will fix this particular oddness.  cc @rwhogg for thoughts.

**Comment by ilovezfs** [comment]
@dunn it feels "rude" to turn it off, but anecdotally it does seem to feel like noise as opposed to something that's impacting the final thing we merge.

**Pull request closed without merging**
