### PR TITLE
dart-mode 0.15 (new formula)

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by dunn** [comment]
```
==> Byte compiling dart-mode.el

In toplevel form:
dart-mode.el:247:1:Error: Wrong type argument: listp, anchor

Error: Byte compilation failed

**Comment by dunn** [comment]
HEAD compiles fine, so maybe 0.14 (which is old) isn't compatible with Emacs 25?

**Comment by rwhogg** [comment]
I made a PR to bump the version number to 0.15, which was accepted. While there's no new tag, I don't think it's a big deal if we treat the commit sha as one.

**Comment by dunn** [comment]
There's a tag now!

**Comment by rwhogg** [comment]
Thanks for following up on that @dunn :smile: 

> Error: Failed to download resource "flycheck--pos-tip"
Download failed: https://github.com/flycheck/flycheck-pos-tip/archive/hotfix-0.25.1.tar.gz

I'll try and follow up on that myself.

**Comment by dunn** [comment]
Looks like he deleted the tag; but he added https://github.com/flycheck/flycheck-pos-tip/archive/0.3.tar.gz

**Pull request closed without merging**
